/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./menu.html",
    "./about.html",
    "./gallery.html",
    "./contact.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b3c5ff",
        "secondary": "#5c5f60",
        "primary": "#00328a",
        "on-tertiary-container": "#c2c2cc",
        "on-error-container": "#93000a",
        "tertiary": "#373941",
        "surface": "#f8f9ff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#44464f",
        "surface-variant": "#d3e4fe",
        "on-error": "#ffffff",
        "on-surface": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "outline": "#737685",
        "secondary-fixed-dim": "#c5c7c8",
        "secondary-fixed": "#e1e3e4",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-low": "#eff4ff",
        "on-background": "#0b1c30",
        "on-secondary-container": "#626566",
        "accent-yellow": "#fbbf24",
        "on-tertiary-fixed": "#191b23",
        "surface-container": "#e5eeff",
        "surface-dim": "#cbdbf5",
        "inverse-surface": "#213145",
        "background": "#f8f9ff",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#003ea6",
        "on-secondary-fixed-variant": "#444748",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#00174a",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#191c1d",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c3c6d6",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c5c6d0",
        "primary-container": "#0047bb",
        "on-primary-container": "#afc1ff",
        "on-surface-variant": "#434653",
        "secondary-container": "#e1e3e4",
        "surface-tint": "#2156ca",
        "surface-container-highest": "#d3e4fe",
        "inverse-primary": "#b3c5ff",
        "tertiary-fixed": "#e1e2ec",
        "tertiary-container": "#4e5058",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1280px",
        "gutter": "24px",
        "unit": "8px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "body-lg": ["Manrope"],
        "label-sm": ["Inter"],
        "headline-lg-mobile": ["Manrope"],
        "headline-lg": ["Manrope"],
        "headline-xl": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-xl-mobile": ["Manrope"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-xl-mobile": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
